###
GET http://localhost:9000/api/cuota HTTP/1.1

###
GET http://localhost:9000/api/coop HTTP/1.1

###
GET http://localhost:9000/api/reporteCuotas/1 HTTP/1.1

--------------------------------------------------------

###
POST http://localhost:9000/api/coop HTTP/1.1
Content-Type: application/json


{
    "nombre_cooperativa": "me crearon hoy",
    "rut_cooperativa": "22"
}


----------------------------------------------------

###
DELETE http://localhost:9000/api/coop/9 HTTP/1.1



-----------------------------------------------------

###
PUT http://localhost:9000/api/coop/26 HTTP/1.1
Content-Type: application/json

{
    "nombre_cooperativa":"Cooperativa de Trabajo  Hub Isprirare LTDA",
    "rut_cooperativa": "76509617-0"
}